#ifndef CLIENT_RUNNER_TYPES_H
#define CLIENT_RUNNER_TYPES_H
enum ClientRunnerMode
{
	MAIN_MENU=0, REGISTER_USER=1, CONNECT_USER=2, DISCONNECT_USER=3, SHOW_USER_PROFILE=4, SHOW_FILM=5, SHOW_RECOMMENDATIONS=6, SHOW_TRENDS=7, SHOW_MY_FILMS=8, SHOW_RANDOM=9
};
#define CLIENT_ENUM_SIZE 10
#endif
